repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        exclude: ^docs/conf.py$
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        args: [--target-version, py38]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
#-   repo: https://github.com/PyCQA/isort
#    rev: 5.6.4
#    hooks:
#    -   id: isort
