[tox]
min_version = 4.0
# py311, py312, py313, py314,
env_list =  py315

requires =
    tox-uv>=1.28


[testenv]
runner = uv-venv-lock-runner
dependency_groups = dev
commands =
    pytest {posargs:test}
    mypy whats_that_code test
