"""Classify every snippet in test/data/characterization and write docs/accuracy.md.

Runs three detection axes per file:
  * code_only    — no hints, just the source text
  * with_filename — filename (extension) hint added
  * with_tag     — language tag hint added

Emits a compact Markdown table with pass/fail per axis and % summary rows.

Usage:
    python scripts/examples.py
"""

from __future__ import annotations

import random
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from whats_that_code.election import guess_language_all_methods
from whats_that_code.languages import canonical

REPO = Path(__file__).resolve().parent.parent
CORPUS = REPO / "test" / "data" / "characterization"
OUT = REPO / "docs" / "accuracy.md"

# Reproduce the same synonym mapping as evaluate.py so ✓/✗ is fair.
_EVAL_SYNONYMS: dict[str, str] = {
    "csharp": "c#",
    "shell": "bash",
    "sh": "bash",
}

AXES = ("code_only", "with_filename", "with_tag")
AXIS_HEADERS = ("code only", "w/ filename", "w/ tag")

TICK = "✓"
CROSS = "✗"


def norm(label: str | None) -> str | None:
    if label is None:
        return None
    c = canonical(label)
    return _EVAL_SYNONYMS.get(c, c)


def classify(code: str, filename: str, lang_dir: str) -> dict[str, str | None]:
    return {
        "code_only": guess_language_all_methods(code),
        "with_filename": guess_language_all_methods(code, file_name=filename),
        "with_tag": guess_language_all_methods(code, tags=[lang_dir]),
    }


def iter_snippets():
    for path in sorted(CORPUS.rglob("*")):
        if not path.is_file() or path.name == "expected.json":
            continue
        rel = path.relative_to(CORPUS).as_posix()
        lang_dir = path.relative_to(CORPUS).parts[0]
        yield rel, lang_dir, path.name, path.read_text(encoding="utf-8")


def build_rows() -> tuple[list[dict], int]:
    rows = []
    total = 0
    for rel, lang_dir, filename, code in iter_snippets():
        expected = norm(lang_dir)
        results = classify(code, filename, lang_dir)
        total += 1
        row = {
            "file": rel,
            "expected": expected,
            "results": {},
            "correct": {},
        }
        for ax in AXES:
            got = norm(results[ax])
            ok = got is not None and got == expected
            row["results"][ax] = got or "—"
            row["correct"][ax] = ok
        rows.append(row)
    return rows, total


def render_markdown(rows: list[dict]) -> str:
    lines: list[str] = []

    ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines += [
        "# Detection Accuracy",
        "",
        f"> Generated by `scripts/examples.py` on {ts}.",
        "> Corpus: `test/data/characterization/`.",
        ">",
        "> Three detection axes are tested per file:",
        "> - **code only** — no hints beyond the source text",
        "> - **w/ filename** — filename (and its extension) passed as a hint",
        "> - **w/ tag** — language directory name passed as a tag hint",
        ">",
        f"> {TICK} = correct &nbsp; {CROSS} = incorrect",
        "",
    ]

    # ── per-file table ───────────────────────────────────────────────────────
    def cell(ok: bool, got: str) -> str:
        mark = TICK if ok else CROSS
        return f"{mark} `{got}`"

    lines += [
        "## Per-file results",
        "",
        "| File | Expected | Code only | w/ filename | w/ tag |",
        "| ---- | -------- | --------- | ----------- | ------ |",
    ]

    correct_totals = {ax: 0 for ax in AXES}
    for row in rows:
        cells = [cell(row["correct"][ax], row["results"][ax]) for ax in AXES]
        lines.append(
            f"| `{row['file']}` | {row['expected'] or '—'} "
            f"| {cells[0]} | {cells[1]} | {cells[2]} |"
        )
        for ax in AXES:
            if row["correct"][ax]:
                correct_totals[ax] += 1

    n = len(rows)
    pcts = {ax: correct_totals[ax] / n for ax in AXES}

    def pct_cell(ax: str) -> str:
        p = pcts[ax]
        return f"**{p:.0%}** ({correct_totals[ax]}/{n})"

    lines += [
        f"| **Total** | | {pct_cell('code_only')} | {pct_cell('with_filename')} | {pct_cell('with_tag')} |",
        "",
    ]

    # ── summary table ────────────────────────────────────────────────────────
    lines += [
        "## Summary",
        "",
        "| Axis | Correct | Total | Accuracy |",
        "| ---- | ------: | ----: | -------: |",
    ]
    axis_labels = {
        "code_only": "Code only",
        "with_filename": "With filename",
        "with_tag": "With tag",
    }
    for ax in AXES:
        lines.append(
            f"| {axis_labels[ax]} | {correct_totals[ax]} | {n} | **{pcts[ax]:.1%}** |"
        )

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    # Seed random for reproducible IRV tie-breaks (mirrors evaluate.py default).
    random.seed(0)

    print("Classifying corpus…", flush=True)
    rows, total = build_rows()

    md = render_markdown(rows)
    OUT.write_text(md, encoding="utf-8")

    n = len(rows)
    for ax in AXES:
        ok = sum(1 for r in rows if r["correct"][ax])
        print(f"  {ax:16} {ok}/{n}  ({ok/n:.0%})")
    print(f"\nWrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
