"""Freeze the characterization (golden) outputs for the snippet corpus.

The election in ``whats_that_code`` is **not** deterministic across Python hash
seeds: when it falls back to the "dumb" voters (keyword / pygments) the candidate
order comes from ``set`` iteration, so IRV ties resolve differently per
``PYTHONHASHSEED`` (see spec/phase0_findings.md). A naive golden test would be
flaky.

This generator runs each snippet under several hash seeds (in subprocesses) and
records, per (snippet, axis), the output **only if it is identical across all
seeds**. Stable entries become the regression oracle in
``test/test_fast/test_characterization.py``; unstable entries are recorded but not
asserted strictly.

Usage:
    python scripts/gen_characterization.py            # (re)write expected.json
    python scripts/gen_characterization.py --emit DIR # internal: print one seed's outputs as JSON
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CORPUS = REPO / "test" / "data" / "characterization"
EXPECTED = CORPUS / "expected.json"
SEEDS = [0, 1, 2, 3, 7, 42, 123, 1000]
AXES = ("code_only", "with_filename", "with_tag")


def iter_snippets(base: Path):
    """Yield (relpath, language_dir, filename, code) for each snippet file."""
    for path in sorted(base.rglob("*")):
        if not path.is_file() or path.name == "expected.json":
            continue
        rel = path.relative_to(base).as_posix()
        language_dir = path.relative_to(base).parts[0]
        code = path.read_text(encoding="utf-8")
        yield rel, language_dir, path.name, code


def outputs_for(code: str, language_dir: str, filename: str) -> dict[str, str | None]:
    """Compute the three axis outputs for one snippet (in-process, current seed)."""
    from whats_that_code.election import guess_language_all_methods

    return {
        "code_only": guess_language_all_methods(code),
        "with_filename": guess_language_all_methods(code, file_name=filename),
        "with_tag": guess_language_all_methods(code, tags=[language_dir]),
    }


def emit(base: Path) -> None:
    """Print this process's outputs for every snippet as JSON (one hash seed)."""
    result = {rel: outputs_for(code, lang, name) for rel, lang, name, code in iter_snippets(base)}
    json.dump(result, sys.stdout)


def collect_across_seeds(base: Path) -> list[dict]:
    """Run the --emit path once per seed in a subprocess and collect results."""
    runs = []
    for seed in SEEDS:
        env = {**os.environ, "PYTHONHASHSEED": str(seed)}
        proc = subprocess.run(
            [sys.executable, str(Path(__file__)), "--emit", str(base)],
            check=True,
            capture_output=True,
            text=True,
            env=env,
            cwd=str(REPO),
        )
        runs.append(json.loads(proc.stdout))
    return runs


def build_expected(base: Path) -> dict:
    runs = collect_across_seeds(base)
    entries: dict[str, dict] = {}
    stable_count = 0
    unstable_count = 0
    for rel, _lang, _name, _code in iter_snippets(base):
        entries[rel] = {}
        for axis in AXES:
            observed = sorted({json.dumps(run[rel][axis]) for run in runs})
            values = [json.loads(o) for o in observed]
            if len(values) == 1:
                entries[rel][axis] = {"stable": True, "value": values[0]}
                stable_count += 1
            else:
                entries[rel][axis] = {"stable": False, "observed": values}
                unstable_count += 1
    return {
        "_meta": {
            "seeds": SEEDS,
            "axes": list(AXES),
            "stable_entries": stable_count,
            "unstable_entries": unstable_count,
            "note": (
                "Generated by scripts/gen_characterization.py. 'stable' entries are identical "
                "across all listed PYTHONHASHSEED values and are asserted by "
                "test_characterization.py. 'unstable' entries vary by hash seed (election "
                "fallback nondeterminism, see spec/phase0_findings.md) and are not asserted."
            ),
        },
        "entries": entries,
    }


def main(argv: list[str]) -> int:
    if argv and argv[0] == "--emit":
        emit(Path(argv[1]))
        return 0
    expected = build_expected(CORPUS)
    EXPECTED.write_text(json.dumps(expected, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    meta = expected["_meta"]
    print(f"Wrote {EXPECTED}")
    print(f"  stable axis-entries:   {meta['stable_entries']}")
    print(f"  unstable axis-entries: {meta['unstable_entries']}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
