name: Build and Test

on: [ push ]

permissions:
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
                with:
                    persist-credentials: false
            -   uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
                with:
                    python-version: '3.11'
                    cache: 'pipenv' # caching pipenv dependencies
            -   name: Install pipenv and pipx
                run: |
                    pip install pipenv && pip install pipx

            -   name: Install global dependencies
                run: |
                    pipx install isort && pipx install black && pipx install bandit && pipx install pylint && \
                    pipx install pre-commit && pipx install pygount && pipx install vulture && \
                    pipx install flake8 && \
                    pipx inject flake8 dlint mccabe pyflakes pep8-naming flake8-bugbear && \
                    pipx install "pipenv-to-requirements==0.9.*" && \
                    pipx inject pipenv-to-requirements "pipenv==2022.9.8" && \
                    pipx install safety && pipx install pyupgrade && pipx install poetry

            -   name: Install Dependencies
                run: pipenv install --dev --skip-lock

            -   name: Run nb
                run: pipenv run nb package
            -   name: Upload Package
                uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
                with:
                  name: packages
                  path: dist/
                  if-no-files-found: error
                  retention-days: 1


    pypi-publish:
        name: Upload release to PyPI
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/whats_that_code
        permissions:
            id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        steps:
            -   name: Get packages
                uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
                with:
                    name: packages
                    path: dist/
            -   name: Publish package distributions to PyPI
                uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        needs: build
